export enum RentalPostStatusEnum {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  DELISTED = 'DELISTED',
  DISPUTED_FOR_LENDER = 'DISPUTED_FOR_LENDER',
  DISPUTED_FOR_RENTER = 'DISPUTED_FOR_RENTER',
}
