[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "lib/forge-std/src/=lib/forge-std/src/",
    "forge-std=lib/forge-std/src/"
]
ffi = true
optimizer = true
optimizer_runs = 1_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
