export const LENDR_FACTORY_CONTRACT_ADDRESS = '0x22d38482d1372267C18F900A8bFf3f17988a491c';
export const LENDR_DELEGATION_CONTRACT_ADDRESS = '0x22d38482d1372267C18F900A8bFf3f17988a491c';
export const LENDR_COLLATERAL_CONTRACT_ADDRESS = '0x22d38482d1372267C18F900A8bFf3f17988a491c';

export const LENDR_FACTORY_ABI = [
  {
    inputs: [{ internalType: 'uint256', name: 'initialPlatformFeePercentInBps', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'LendrRentalSystem__CollateralMustBeGreaterThanZero', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__FeeMustBeGreaterThanZero', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__InvalidDepositDeadline', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__InvalidNftStandard', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
    name: 'LendrRentalSystem__NotDeployer',
    type: 'error',
  },
  { inputs: [], name: 'LendrRentalSystem__NotLender', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__RentalDurationMustBeGreaterThanZero', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__WithdrawFailed', type: 'error' },
  { inputs: [], name: 'LendrRentalSystem__ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: false, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'collateral', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'rentalDurationInHours', type: 'uint256' },
      { indexed: false, internalType: 'enum RentalEnums.NftStandard', name: 'nftStandard', type: 'uint8' },
      { indexed: false, internalType: 'enum RentalEnums.DealDuration', name: 'dealDuration', type: 'uint8' },
    ],
    name: 'CollateralRentalAgreementCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: false, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'rentalDurationInHours', type: 'uint256' },
      { indexed: false, internalType: 'enum RentalEnums.NftStandard', name: 'nftStandard', type: 'uint8' },
      { indexed: false, internalType: 'enum RentalEnums.DealDuration', name: 'dealDuration', type: 'uint8' },
    ],
    name: 'DelegationRentalAgreementCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'newFeePercent', type: 'uint256' }],
    name: 'FeeUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'delegationRegistry', type: 'address' },
      { indexed: true, internalType: 'address', name: 'collateralRegistry', type: 'address' },
    ],
    name: 'RegistriesDeployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'Withdrawn',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: '_collateral', type: 'uint256' },
      { internalType: 'uint256', name: '_rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: '_nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: '_dealDuration', type: 'uint8' },
    ],
    name: 'createCollateralRentalAgreement',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: '_rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: '_nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: '_dealDuration', type: 'uint8' },
    ],
    name: 'createDelegationRentalAgreement',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_collateralRegistry',
    outputs: [{ internalType: 'contract CollateralRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_delegationRegistry',
    outputs: [{ internalType: 'contract DelegationRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_deployer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 's_collateralRentalAgreementById',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_feeBps',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 's_totalRentals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newFeeBps', type: 'uint256' }],
    name: 'setFeeBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { stateMutability: 'payable', type: 'receive' },
] as const;

export const LENDR_COLLATERAL_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'CollateralRegistry__AgreementAlreadyExists', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__AgreementDoesNotExist', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__CollateralRentalDoesNotSupportNFTType', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__DeadlinePassed', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__InvalidDealDuration', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__InvalidPayment', type: 'error' },
  {
    inputs: [
      { internalType: 'enum CollateralRegistry.State', name: 'expected', type: 'uint8' },
      { internalType: 'enum CollateralRegistry.State', name: 'actual', type: 'uint8' },
    ],
    name: 'CollateralRegistry__InvalidState',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__InvalidStateForDefault', type: 'error' },
  {
    inputs: [
      { internalType: 'address', name: 'expected', type: 'address' },
      { internalType: 'address', name: 'actual', type: 'address' },
    ],
    name: 'CollateralRegistry__InvalidUser',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__LenderStillHasTime', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NftNotInEscrow', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NotAuthorized', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NotOwner', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__PaymentFailed', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__RentalNotEnded', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__RenterMustNotBeLender', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__RenterStillHasTime', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__ReturnDeadlineMissed', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'factory', type: 'address' }],
    name: 'AuthorizationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'CollateralClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'NftDepositedByLender',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'NftReleasedToRenter',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'renter', type: 'address' },
      { indexed: true, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'NftReturnedByRenter',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: true, internalType: 'address', name: 'platform', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'lenderPayout', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'platformFee', type: 'uint256' },
    ],
    name: 'PayoutsDistributed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'renter', type: 'address' },
    ],
    name: 'RentalInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
    ],
    name: 'RentalStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: false, internalType: 'enum CollateralRegistry.State', name: 'oldState', type: 'uint8' },
      { indexed: false, internalType: 'enum CollateralRegistry.State', name: 'newState', type: 'uint8' },
    ],
    name: 'StateChanged',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'address', name: '_factoryAddress', type: 'address' }],
    name: 'addAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'cancelRentalAfterClaimTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'claimCollateralWhenDefaulted',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'claimNFTWhenRenterUnableToClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_rentalId', type: 'uint256' },
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: '_collateral', type: 'uint256' },
      { internalType: 'uint256', name: '_rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: '_nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: '_dealDuration', type: 'uint8' },
    ],
    name: 'createAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'depositNFTByLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'getTotalHourlyFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'getTotalRentalFeeWithCollateral',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'initiateRental',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155BatchReceived',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC721Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'reclaimFundsOnLenderTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'releaseNFTToRenter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'releaseNFTToRenterFromLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_factoryAddress', type: 'address' }],
    name: 'removeAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'returnNFTToLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 's_agreements',
    outputs: [
      { internalType: 'address', name: 'lender', type: 'address' },
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: 'collateral', type: 'uint256' },
      { internalType: 'uint256', name: 'rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: 'nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: 'dealDuration', type: 'uint8' },
      { internalType: 'address', name: 'renter', type: 'address' },
      { internalType: 'enum CollateralRegistry.State', name: 'rentalState', type: 'uint8' },
      { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
      { internalType: 'uint256', name: 'lenderDepositDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'returnDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'renterClaimDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
      { internalType: 'address', name: 'factoryAddress', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_isAuthorized',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export const LENDR_DELEGATION_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'DelegationRegistry__ActiveDelegation', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__AgreementDoesNotExist', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__DeadlinePassed', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__DelegationDeadlineNotPassed', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__DelegationRentalDoesNotSupportNFTType', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__DurationCannotBeZero', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__InvalidAmount', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__InvalidDealDuration', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__InvalidNftContract', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__InvalidPayment', type: 'error' },
  {
    inputs: [
      { internalType: 'enum DelegationRegistry.State', name: 'expected', type: 'uint8' },
      { internalType: 'enum DelegationRegistry.State', name: 'actual', type: 'uint8' },
    ],
    name: 'DelegationRegistry__InvalidState',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'expected', type: 'address' },
      { internalType: 'address', name: 'actual', type: 'address' },
    ],
    name: 'DelegationRegistry__InvalidUser',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__NftNotDeposited', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NoBreachDetected', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotAuthorized', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotOriginalOwner', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotOwner', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__PaymentFailed', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__RentalIsOver', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__RentalNotOver', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__RenterMustNotBeLender', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__WithdrawalFailed', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'removedAuthorizedAddress', type: 'address' }],
    name: 'AuthorizationRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'newAuthorizedAddress', type: 'address' }],
    name: 'AuthorizationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'DelegationRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'uint64', name: 'expires', type: 'uint64' },
    ],
    name: 'DelegationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'NftDeposited',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'NftDepositedByLender',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'nftContract', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'NftWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'lender', type: 'address' },
      { indexed: true, internalType: 'address', name: 'platform', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'lenderPayout', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'platformFee', type: 'uint256' },
    ],
    name: 'PayoutsDistributed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'renter', type: 'address' },
    ],
    name: 'RentalInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
    ],
    name: 'RentalStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { indexed: false, internalType: 'enum DelegationRegistry.State', name: 'oldState', type: 'uint8' },
      { indexed: false, internalType: 'enum DelegationRegistry.State', name: 'newState', type: 'uint8' },
    ],
    name: 'StateChanged',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'activateDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_factoryAddress', type: 'address' }],
    name: 'addAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'cancelDelegationRental',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'completeDelegationRental',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: '_rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: '_nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: '_dealDuration', type: 'uint8' },
    ],
    name: 'createRentalAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'depositNFTByLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'depositNFTtoEscrow',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'getDelegation',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'uint64', name: 'expires', type: 'uint64' },
        ],
        internalType: 'struct DelegationRegistry.Delegation',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'getRentalAgreement',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'lender', type: 'address' },
          { internalType: 'address', name: 'nftContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
          { internalType: 'uint256', name: 'rentalDurationInHours', type: 'uint256' },
          { internalType: 'enum RentalEnums.NftStandard', name: 's_nftStandard', type: 'uint8' },
          { internalType: 'enum RentalEnums.DealDuration', name: 'dealDuration', type: 'uint8' },
          { internalType: 'address', name: 'renter', type: 'address' },
          { internalType: 'enum DelegationRegistry.State', name: 'rentalState', type: 'uint8' },
          { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
          { internalType: 'uint256', name: 'lenderDelegationDeadline', type: 'uint256' },
          { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
          { internalType: 'address', name: 'factoryAddress', type: 'address' },
        ],
        internalType: 'struct DelegationRegistry.RentalAgreement',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'getTotalHourlyFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'initiateDelegationRental',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155BatchReceived',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC721Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'originalOwnerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_factoryAddress', type: 'address' }],
    name: 'removeAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'reportBreach',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'revokeDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_isAuthorized',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_nftStandard',
    outputs: [{ internalType: 'enum RentalEnums.NftStandard', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 's_rentalAgreements',
    outputs: [
      { internalType: 'address', name: 'lender', type: 'address' },
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: 'rentalDurationInHours', type: 'uint256' },
      { internalType: 'enum RentalEnums.NftStandard', name: 's_nftStandard', type: 'uint8' },
      { internalType: 'enum RentalEnums.DealDuration', name: 'dealDuration', type: 'uint8' },
      { internalType: 'address', name: 'renter', type: 'address' },
      { internalType: 'enum DelegationRegistry.State', name: 'rentalState', type: 'uint8' },
      { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
      { internalType: 'uint256', name: 'lenderDelegationDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
      { internalType: 'address', name: 'factoryAddress', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint64', name: 'expires', type: 'uint64' },
    ],
    name: 'setDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'userExpires',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'userOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'withdrawNft',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
