import type { Metadata } from "next";
import { Geist, Azeret_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/navbar";
import dynamic from "next/dynamic";
import '@rainbow-me/rainbowkit/styles.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const azeretMono = Azeret_Mono({
    variable: "--font-azeret-mono",
    subsets: ['latin']
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const WagmiProvider = dynamic(() =>
    import('../providers/wagmi-provider').then((mod) => mod.CustomWagmiProvider)
);

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${azeretMono.variable} font-sans`}>
                <WagmiProvider>
                    <NavBar />
                    {children}
                </WagmiProvider>
                \
            </body>
        </html>
    );
}