#!/bin/sh

echo '👷‍♂️ Starting pre-commit checks...'

STAGED_FILES=$(git diff --cached --name-only)
echo '🔍 Staged files:'
echo "$STAGED_FILES"

echo '📦 Changes detected in /api...'
echo '🧹 Linting API service...'
bun lint || exit 1
echo '🎨 Formatting API service...'
bun format || exit 1

echo '✅ All relevant checks passed. Proceeding with commit. 🚀'